from fastapi import APIRouter
from . import agents, knowledge_base, workflows, monitoring, enhanced_monitoring, versioning, alerting, cost_tracking, auth, scheduling, audit, queue, templates, human_in_loop, langfuse_analytics, a2a, mcp, credentials, webhooks, models, mcp_servers

router = APIRouter()
router.include_router(auth.router, prefix="/auth", tags=["authentication"])
router.include_router(models.router, prefix="/models", tags=["models"])
router.include_router(agents.router, prefix="/agents", tags=["agents"])
router.include_router(mcp_servers.router, prefix="/mcp-servers", tags=["mcp-servers"])
router.include_router(knowledge_base.router, prefix="/knowledge-bases", tags=["knowledge-bases"])
router.include_router(workflows.router, prefix="/workflows", tags=["workflows"])
router.include_router(credentials.router, prefix="/credentials", tags=["credentials"])
router.include_router(webhooks.router, prefix="/webhooks", tags=["webhooks"])
router.include_router(monitoring.router, prefix="/monitoring", tags=["monitoring"])
router.include_router(enhanced_monitoring.router, prefix="/enhanced-monitoring", tags=["enhanced-monitoring"])
router.include_router(versioning.router, prefix="/versioning", tags=["versioning"])
router.include_router(alerting.router, prefix="/alerting", tags=["alerting"])
router.include_router(cost_tracking.router, prefix="/cost-tracking", tags=["cost-tracking"])
router.include_router(scheduling.router, prefix="/scheduling", tags=["scheduling"])
router.include_router(audit.router, prefix="/audit", tags=["audit"])
router.include_router(queue.router, prefix="/queue", tags=["queue"])
router.include_router(templates.router, prefix="/templates", tags=["templates"])
router.include_router(human_in_loop.router, prefix="/human-in-loop", tags=["human-in-loop"])
router.include_router(langfuse_analytics.router, prefix="/langfuse", tags=["langfuse"])
router.include_router(a2a.router, prefix="/a2a", tags=["a2a"])
router.include_router(mcp.router, prefix="/mcp", tags=["mcp"])